apiVersion: v1
kind: Service
metadata:
  name: vak-kernel
  namespace: vak-system
  labels:
    app.kubernetes.io/name: vak
    app.kubernetes.io/component: kernel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vak
    app.kubernetes.io/component: kernel
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
